// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tanjpynitwmmhejhbaqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhbmpweW5pdHdtbWhlamhiYXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NTc3NjcsImV4cCI6MjA1NzAzMzc2N30.TVkro3ZAFDerWkVAORytx989Shu1QqKOD43oGt3ZQRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);